import { type NextPage } from "next";

import Head from "next/head";
import Link from "next/link";

const Editor: NextPage = () => {
  return (
    <>
      <Head>
        <title>Editor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Editor page</h1>
    </>
  );
};

export default Editor;
