import { type NextPage } from "next";

import Head from "next/head";

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "~/components/ui/accordion";

import { Textarea } from "~/components/ui/textarea";

import { Button } from "~/components/ui/button";

const Editor: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex w-full grow">
        <article className="flex flex-col w-6/12">
          <Card className="grow m-1 flex flex-col">
            <CardHeader>
              <CardTitle>Request Editor</CardTitle>
              <CardDescription>Wite your Grqphql request</CardDescription>
            </CardHeader>
            <CardContent className="flex grow flex-col">
              <Textarea className="grow"/>
            </CardContent>
            <CardFooter>
              <Button>Send</Button>
            </CardFooter>
          </Card>

          <Card className="m-1">
            <CardContent>
              <Accordion type="single" collapsible>
                <AccordionItem value="item-1">
                  <AccordionTrigger>Variables Editor</AccordionTrigger>
                  <AccordionContent className="p-1">
                    <Textarea />
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </CardContent>
          </Card>


          <Card className="m-1">
            <CardContent>
              <Accordion type="single" collapsible>
                <AccordionItem value="item-1">
                  <AccordionTrigger>Headers Editor</AccordionTrigger>
                  <AccordionContent className="p-1">
                    <Textarea />
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </CardContent>
          </Card>
        </article>

        <article className="flex flex-col w-6/12">
          <Card className="grow m-1">
            <CardHeader>
              <CardTitle>Response Section</CardTitle>
              <CardDescription>This is the section for response</CardDescription>
            </CardHeader>
            <CardContent>
              <p>Some response...</p>
            </CardContent>
            <CardFooter>
              <p>Card Footer if needed</p>
            </CardFooter>
          </Card>

          <Card className="m-1">
            <CardHeader>
              <CardTitle>Documentation Explorer</CardTitle>
              <CardDescription>should be lazy-loaded</CardDescription>
            </CardHeader>
            <CardContent>
              <p>Some docs</p>
            </CardContent>
            <CardFooter>
              <p>Card Footer if needed</p>
            </CardFooter>
          </Card>

        </article>
      </section>
    </>
  );
};

export default Editor;
