import { type NextPage } from "next";

import Head from "next/head";
import Link from "next/link";

import { useSession } from "next-auth/react";

import Login from "~/components/Login/Login";

import { Button } from "~/components/ui";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>GraphiQL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon32.png" />
      </Head>
      {session ? (
        <Button className="self-end mt-4 mr-6">
          <Link href="/editor">Go to the editor</Link>
        </Button>
      ) : (
        <div className="self-end mt-4 mr-2">
          <Login mode="sign-in">
            <Button>Sign In</Button>
          </Login>
          <Login mode="sign-up">
            <Button>Sign Up</Button>
          </Login>
        </div>
      )}
    </>
  );
};

export default Home;
