/* import { type NextPage } from "next";
import { useEffect } from "react";
import { useSession } from "next-auth/react";
import { signIn, signOut } from "next-auth/react";
import { useRouter } from "next/router";

import Login from "../components/Login/Login";

import Head from "next/head";

const Login: NextPage = () => {
  const { data: session } = useSession();
  const router = useRouter();
  useEffect(() => {
    if (session) router.push("/");
  });

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => signIn()}>Sign In</button>
    </>
  );
};

export default Login;
 */
