import { type NextPage } from "next";

import { signIn, signOut } from "next-auth/react";

import Head from "next/head";
import Link from "next/link";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => signIn()}>Sign In</button>
    </>
  );
};

export default Login;
